rules: ["variant_stats", "tranche_extract", "post_filtering_stats", "phasing", "convert_mm"]

1kbulls_dir: /storage/htc/schnabellab/results/9913/wgs/1kbulls_ars1.2/vcf/200627_Run8_TauInd

run_name: "200708_Run8_refbuild"

eagle_threads: 48

mm_threads: 8

bcftools_threads: 8

allele_count: "20"

tranche: "T90"

filter: "PASS,VQSRTrancheINDEL90.00to99.00,VQSRTrancheSNP90.00to99.00"
