rules: ["tranche_extract", "phasing", "convert_mm"]

1kbulls_dir: "/storage/htc/schnabellab/results/9913/wgs/1kbulls_ars1.2/vcf/190522_Run7_Tau"

run_name: "200708_Run8"

eagle_threads: 16

mm_threads: 8

bcftools_threads: 8

allele_count: "AC20"

tranche: "T90"
